spring:
  datasource:
    #本地数据库连接
    #url: jdbc:mysql://127.0.0.1:3306/testdb?zeroDateTimeBehavior=convertToNull&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    #url: jdbc:mysql://127.0.0.1:3306/testdb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    #username: root
    #password: dbmysql
    #driver-class-name: com.mysql.jdbc.Driver
    #driver-class-name: com.mysql.cj.jdbc.Driver

    #    #本地组数据库连接
    #    url: jdbc:mysql://10.1.4.27:3307/wuzhen?useUnicode=true&characterEncoding=utf-8&useSSL=false
    #    username: root
    #    password: cmri!Q@W#E
    #    driver-class-name: com.mysql.jdbc.Driver

    #乌镇数据库连接
    url: jdbc:mysql://177.1.0.200/wuzhen?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Root123
    driver-class-name: com.mysql.jdbc.Driver
    # druid
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  #redis
  redis:
    database: 0 #默认数据库
    #    host: 127.0.0.1
    #    port: 6379
    password: 123456!@#
    timeout: 3600 #超时
    cluster:
      nodes: 177.1.0.140:7001,177.1.0.140:7002,177.1.0.150:7001,177.1.0.150:7002,177.1.0.160:7001,177.1.0.160:7002
    commandTimeout: 5000

    #  redis:
    #    database: 0 #默认数据库
    #    host: 127.0.0.1
    #    port: 6379
    #    password: 123456 #密码
    #    timeout: 3600 #超时
    jedis:
      pool:
        max-active: 10 #最大活动对象数
        max-idle: 10 #最大能够保持idel状态的对象数
        min-idle: 1 #最小能够保持idel状态的对象数
        max-wait: 10000 #当池内没有返回对象时，最大等待时间
        testOnBorrow: true #当调用borrowObject方法时，是否进行有效性检查
        testOnReturn: true #当调用returnObject方法时，是否进行有效性检查
        timeBetweenEvictionRunsMillis: 30000 #“空闲链接”检测线程，检测的周期，毫秒数。如果为负值，表示不运行“检测线程”。默认为-1.
        testWhileIdle: true #向调用者输出“链接”对象时，是否检测它的空闲超时；
        numTestsPerEvictionRun: 10 #对于“空闲链接”检测线程而言，每次检测的链接资源的个数。默认为3.
mybatis:
  #type-aliases-package: com.example.spring.demospringboot.entity
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8762

  spring:
    application:
    name: eureka-client-apioverview
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#  server:
#   enableSelfPreservation: true
#   evictionIntervalTimerInMs: 4000
#  instance:
#   hostname: localhost
#   leaseRenewalIntervalInSeconds: 1
#   leaseExpirationDurationInSeconds: 2
#  client:
#    registerWithEureka: true
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#  spring:
#   application:
#     name: eureka-server








